# SPDX-License-Identifier: GPL-2.0

obj-m += xiaomi_touch.o
xiaomi_touch-objs := xiaomi_touch_core.o \
					xiaomi_touch_knock_data.o \
					xiaomi_touch_proc.o xiaomi_touch_operations.o \
					xiaomi_touch_sys.o xiaomi_touch_mode.o \
					xiaomi_touch_evdev.o xiaomi_touch_device.o
