

############ CS35L41 ############

# for CS35L41 Codec
ifdef CONFIG_SND_SOC_CS35L41
	CS35L41_OBJS += cs35l41.o
	CS35L41_OBJS += cs35l41-i2c.o
	CS35L41_OBJS += cs35l41-tables.o
	CS35L41_OBJS += wm_adsp.o
	#CS35L41_OBJS += send_data_to_xlog.o
endif

ifeq ($(TARGET_PRODUCT), $(filter $(TARGET_PRODUCT), taro))
       CDEFINES += -DCONFIG_AUDIO_SMARTPA_STEREO
endif

CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
		-DANI_LITTLE_BIT_ENDIAN \
		-DDOT11F_LITTLE_ENDIAN_HOST \
		-DANI_COMPILER_TYPE_GCC \
		-DANI_OS_TYPE_ANDROID=6 \
		-DPTT_SOCK_SVC_ENABLE \
		-Wall\
		-Werror\
		-D__linux__


ifneq (, $(filter $(word 2,$(subst _, ,$(TARGET_PRODUCT))), houji))
	CDEFINES += -DCONFIG_TARGET_PRODUCT_HOUJI
endif

KBUILD_CPPFLAGS += $(CDEFINES)

# Currently, for versions of gcc which support it, the kernel Makefile
# is disabling the maybe-uninitialized warning.  Re-enable it for the
# AUDIO driver.  Note that we must use EXTRA_CFLAGS here so that it
# will override the kernel settings.
ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif
#EXTRA_CFLAGS += -Wmissing-prototypes

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif


# Module information used by KBuild framework
obj-$(CONFIG_SND_SOC_CS35L41) += cs35l41_dlkm.o
cs35l41_dlkm-y := $(CS35L41_OBJS)

# inject some build related information
DEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
